name: Code Quality

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.15"
      - run: pip install black flake8
      - run: black --check projector.py
      - run: flake8 proector.py
